name: Android CI Build

on:
  push:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Match the engines.node version in package.json
          cache: 'npm' # or 'yarn' if you use yarn

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        # This action will install the necessary Android SDK components.
        # By default, it installs the latest command-line tools, build-tools, and platform-tools.
        # You can specify versions if needed, but defaults are often fine.

      - name: Make gradlew executable
        run: chmod +x ./android/gradlew

      - name: Build Android Debug APK
        run: |
          cd android
          ./gradlew assembleDebug --no-daemon
          # Using --no-daemon can sometimes help with CI environments

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug # Name of the artifact
          path: android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 7 # Optional: How long to keep the artifact
          if-no-files-found: error # Optional: Fail the step if the APK is not found
